// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	MAXMIND_DB: ArrayBuffer;
}
declare module "cloudflare:test" {
	// ...or if you have an existing `Env` type...
	interface ProvidedEnv extends Env { }
}
