// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	MAXMIND_DB: ArrayBuffer;
}
declare module "cloudflare:workers" {
	interface ProvidedEnv extends Env {}
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
